#' Sets dependent task(s) for a given ConnecTask
#'
#' Tasks downstream from a given Connect Task will execute after the provided ConnectTask.
#' When a task is linked as an downstream task, the downstream task also creates an upstream link to the provided task.
#'
#' @param env A ConnectTask environment generated by \link[connectapi.dag]{connect_task}
#'     that you want to set downstream/dependent tasks for.
#' @param ... Any ConnectTasks to make downstream of `env`
#'
#' @return Does not return anything, it modified to ConnecTask Environment in-place
#'
#' @examples
#' task0 <- connect_task("task0", simulated = TRUE)
#' task1 <- connect_task("task1", simulated = TRUE)
#' task2 <- connect_task("task2", simulated = TRUE)
#'
#' task0 |> set_downstream(task1, task2)
#' plot(task0)
#' @export

set_downstream <- function(env, ...) {
  stopifnot(inherits(env, "ConnectTask"))
  env$set_downstream(...)
}
